# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionState',
            fields=[
                ('uuid', models.CharField(default=b'4641f36bc69243709b5b911bb0a47965', max_length=32, primary_key=True, serialize=False)),
                ('action_id', models.PositiveIntegerField(null=True)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
