# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstate',
            name='uuid',
            field=models.CharField(default=b'352935d661ad4ad9adb10aa3639fef0b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
