# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160717_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstate',
            name='uuid',
            field=models.CharField(default=b'16d6f5b4f76b43db8646b026361eed1e', max_length=32, primary_key=True, serialize=False),
        ),
    ]
