# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=260)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cause', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'campaign_covers/')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Beneficiary')),
                ('books', models.ManyToManyField(to='books.Book')),
            ],
        ),
    ]
